### ISSUE TITLE
Some little ideas

### ISSUE THREAD

**Issue by yiranblade** [icorvoh/FSD-Debris#1]
About your instructiions,I have readed.
some suggestions:
1,Software Development Environment not only is IDE, it has something else.
2,you can instruct some foreigin website more than home.
3,why the framework is only frontend?

**Comment by corvoh** [comment]
wow,it would be an english talk.
Foreign website is a good suggestion, i added a little but too few for now...
Maybe due to i had joined more talk group about front-end than back-end, that lead me to write front-end link more... It would be change, and thank u.
So, if U can directly to give me some of the links I don't have , it would be better.
